### ISSUE TITLE
Avoid defining own dunder property(s)

### ISSUE THREAD

**Issue by prostomarkeloff** [DeanWay/fastapi-versioning#1]
**Is your feature request related to a problem? Please describe.**
In code used dunder property `__api_version__` for function.

**Describe the solution you'd like**
Just set the `_api_version`.

**Describe alternatives you've considered**
This looks more pythonic, than your idea.

**Comment by prostomarkeloff** [comment]
https://github.com/DeanWay/fastapi-versioning/blob/7cff1c4892ec46ef43904829ec04afed36eef000/fastapi_versioning/versioning.py#L13

**Comment by DeanWay** [comment]
currently using `_api_version`
