### ISSUE TITLE
Use functools.wraps for decorator

### ISSUE THREAD

**Issue by HacKanCuBa** [DeanWay/fastapi-versioning#11]
Implement functools.wraps in the `version` decorator to [avoid breaking tab completion](https://www.piccolo-orm.com/blog/improving-tab-completion-in-python-libraries/#decorators-can-be-deceiving) and breaking wrapped function signature:

https://github.com/DeanWay/fastapi-versioning/blob/875863c0a312e4d30ecbb351abc3e145fa203b62/fastapi_versioning/versioning.py#L12

**Comment by DeanWay** [comment]
I believe this is addressed in #32. In particular your editor may have misunderstood the type of a function annotated with `@version` since the version function was missing a return type annotation

**Comment by HacKanCuBa** [comment]
> I believe this is addressed in #32. In particular your editor may have misunderstood the type of a function annotated with `@version` since the version function was missing a return type annotation

Yes, I would say it's fixed given #32 adds said annotations.
