### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by joel314** [DeanWay/fastapi-versioning#24]
Hi,

Thanks for this project. Shouldn't it be `version_route_mapping: Dict[Tuple[int, int], List[APIRoute]] = defaultdict(list)` instead of: 

https://github.com/DeanWay/fastapi-versioning/blob/3db32d809caa70217700902a31eb8093d0d647cf/fastapi_versioning/versioning.py#L37

**Comment by DeanWay** [comment]
addressed in #32

**Comment by DeanWay** [comment]
deployed in 0.9.0
