### ISSUE TITLE
A comma is missing here.

### ISSUE THREAD

**Issue by fabiogrigolosc** [DeanWay/fastapi-versioning#3]
https://github.com/DeanWay/fastapi-versioning/blob/67389073cd81ebafe92063729a1cc84c2d5ec826/fastapi_versioning/__init__.py#L6

**Comment by DeanWay** [comment]
👍 thanks

**Comment by DeanWay** [comment]
fixed

**Comment by fabiogrigolosc** [comment]
Can you push a new revision to pypi or are you waiting for other changes?
