### ISSUE TITLE
Support for "latest" version?

### ISSUE THREAD

**Issue by c-tanner** [DeanWay/fastapi-versioning#35]
We have a use case where our API is decoupled from services that call it, which would require another lengthy PR process for our monolith application to update the client to use the newer version of the API.

It would be great to be able to call `/api/latest/endpoint` or `/api/v/latest/endpoint` to automatically use the latest version of the API. This would allow the monolith client code to not have to be changed when we add a new minor/major version to our API.

**Comment by DeanWay** [comment]
@c-tanner @patrickelectric this is released in version 0.9.0 on pypi. You need to enable it by passing the `enable_latest` argument:
```python
app = VersionedFastAPI(app, enable_latest=True)
```

**Comment by qmffkem** [comment]
Hello, I am curious about it but could you tell me why you would want the keyword "latest" to be in the path?
it feels more natural that /api/endpoint serve the latest version of the API by default.
