### ISSUE TITLE
Support for Python 3.6+

### ISSUE THREAD

**Issue by igorcadelima** [DeanWay/fastapi-versioning#5]
Hi, @DeanWay .

First of all, thanks for the initiative!

Would it be possible to also support Python 3.6? In addition to being a personal need, this would be better aligned with [FastAPI's requirements](https://fastapi.tiangolo.com/#requirements). 

Cheers,
Igor.

**Comment by DeanWay** [comment]
version 0.7.0 officially supports python 3.6
