### ISSUE TITLE
Change naming convention of api version in url

### ISSUE THREAD

**Issue by dsouzadyn** [DeanWay/fastapi-versioning#53]
**Is your feature request related to a problem? Please describe.**
In the generated versioning v1_0, v1_2. The underscore is unintuitive when it comes to api versioning.

**Describe the solution you'd like**
Change the underscore to a dot.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ak4zh** [comment]
VersionedFastAPI takes an argument prefix_format, the default is:
```python
prefix_format: str = "/v{major}_{minor}"
```
