### ISSUE TITLE
OAuth2PasswordBearer does not work with versioned api

### ISSUE THREAD

**Issue by ak4zh** [DeanWay/fastapi-versioning#64]
**Describe the bug**
OAuth2PasswordBearer requires a tokenUrl this does not get api versioned automatically.
How should that be handled?

```python
from fastapi.security import OAuth2PasswordBearer

oauth2_scheme = OAuth2PasswordBearer(tokenUrl=f"/auth/login")
```

**Comment by jordantshaw** [comment]
Same question. @Ak4zh  did you figure out a solution for this?

@DeanWay  any input?
